### ISSUE TITLE
Would this work?

### ISSUE THREAD

**Issue by tbrasser** [silvanverschuur/esp-p1-mqtt#1]
It could potentially save most of the hardware:

https://github.com/esp8266/Arduino/pull/6816

**Comment by silvanverschuur** [comment]
Great that they have added an option to invert the signal! I've updated my libraries and I have compiled the code with the invert boolean. 

At the moment I don't have spare hardware to test this but I hope to do this soon.

**Comment by silvanverschuur** [comment]
@tbrasser Today I got some hardware to test this but unfortunately it didn't work. I've added the invert boolean to the Serial.begin statement but I do not receive data from the P1 meter.

**Comment by schnef** [comment]
Inverting the UART's signals is not (yet) implemented in the libraries. However, inverting the RX signal for hardware Serial is a piece of cake:

```
// See: https://github.com/esp8266/Arduino/issues/4896
#define ESP8266_REG(addr) *((volatile uint32_t *)(0x60000000+(addr)))
#define U0C0        ESP8266_REG(0x020) //CONF0
#define UCRXI       19 //Invert RX
```
Than after starting Serial, toggle the invert bit for RX and your done:
```
void setup() {
  ...
  // setup Serial. Invert receive (RX)
  Serial.begin(BAUD_RATE, SERIAL_8N1);
  U0C0 |= BIT(UCRXI); // Inverse RX
  ...
```
Software serial didn't work for me because a) you have to set the `bufCapacity` and `isrBufCapacity` to values which will allow handling a full telegram at a time using the `Serial.readStringUntil()` function, which will consume just about all the memory available and b) it will still fail when the CPU is busy. Using the hardware serial with the inverted RX is very reliable. 

I used a Adafruit HUZZAH ESP8266 breakout board, and external 5V power supply with RX connected directly to the P1 port of a Sagemcom  T210-D.

**Comment by silvanverschuur** [comment]
Thank you very much for the detailed explanation and code examples! 

Sadly I'm out of hardware to test this at the moment but I'm sure this will help other people that do not want to add additional hardware to invert te signal.
